/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FormLink() {
  return (
    <a
      href="#"
      className="overflow-hidden self-stretch px-10 py-3.5 my-auto text-sm font-semibold text-white uppercase bg-black rounded-3xl border border-black border-solid max-md:px-5"
    >
      FORM LINK
    </a>
  );
}

export default FormLink;
