/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Logo() {
  return (
    <div className="flex gap-2.5 justify-center items-center self-stretch my-auto text-xl font-bold">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d00430bd11fc6a1635dba7ee2002310c462c37c18813fc30695714bc7dbdaa11?placeholderIfAbsent=true&apiKey=8f522db98d0241b0b95a275e1bb32c0e"
        alt="GDSC Thapar Logo"
        className="object-contain shrink-0 self-stretch my-auto aspect-[2.15] w-[43px]"
      />
      <div className="self-stretch my-auto">GDSC Thapar</div>
    </div>
  );
}

export default Logo;
